In [1]:
import pandas as pd

In [20]:
df=pd.read_csv("Salary_Data.csv")

In [21]:
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [22]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [23]:
X

YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [24]:
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [29]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [30]:
import numpy as np

In [32]:
model.fit(X_train,y_train)

LinearRegression()

In [34]:
model.fit_intercept

True

In [35]:
model.intercept_  #b

25151.09200962919

In [36]:
model.coef_        #slope(m)

array([9487.78380631])

In [45]:
model.predict([[10]])        #y=mx+c

array([120028.93007268])

In [37]:
model.n_features_in_

1

In [39]:
model.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [40]:
model.n_jobs

In [41]:
model.normalize

False

In [42]:
model.positive

False

In [43]:
model.rank_

1

In [44]:
model.singular_

array([14.01330537])

In [46]:
import joblib

In [48]:
joblib.dump(model,"model.sav")

['model.sav']